config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#welcome'

  get 'registration' => 'user#new', as: :new_user
  post 'registration' => 'user#create', as: :create_user
  get 'users' => 'user#index', as: :users


  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_in' => 'sessions#delete'

end




# get 'entourage' => 'users#following', as: :following
# post 'follow/:user_id' => 'users#follow', as: :follow
# post 'unfollow/:user_id' => 'users#unfollow', as: :unfollow

app/models/user.rb
class User < ActiveRecord::Base
 validates :email, presence: true
 has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    @current_user = User.find_by id: session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def welcome
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create

    user = User.find_by email: params[:email]
    if user && user.authenticate(params[:password])
      # make session[:username] present
      session[:user_id] = user.id
      redirect_to root_path, notice: "Signed in!"
    else
      flash.now[:alert] = "Something is wrong with your username and/or password"
      render :new
    end
  end

  def delete
    # we should sign out
    # make future tests if we are signed in fail
    session.delete :user_id
    redirect_to root_path, notice: "Signed Out!"
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
      @users = User.where("id != ?", @current_user.id)
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new
      @user.email = params[:user][:email]
      @user.password = params[:user][:password]
      @user.password_confirmation = params[:user][:password_confirmation]
      if @user.save
        # we should also sign them in
        session[:user_id] = @user.id
        redirect_to root_path, notice: "Welcome!"
      else
        render :new
      end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/dashboard/welcome.html.erb
<div id='map_id'></div>

<script type="text/javascript">
  var mymap = L.map("map_id").setView([23.13,14.9], 3);
  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoic2Rvc3NldHRzd2lmdCIsImEiOiJjaXFtaDhuZ3UwMHF0ZnFuaHM2MG8zczdyIn0.IB6aK5Z1t1wTRvQ3QBiLZA', {  attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
    maxZoom: 18,
    id: 'sdossettswift.0m9618a5',
    accessToken: 'pk.eyJ1Ijoic2Rvc3NldHRzd2lmdCIsImEiOiJjaXFtaDhuZ3UwMHF0ZnFuaHM2MG8zczdyIn0.IB6aK5Z1t1wTRvQ3QBiLZA',
}).addTo(mymap);

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travelogue</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
</head>
<body>
  <nav>
     <div class="nav-wrapper">
       <a href="#!" class="brand-logo">Wanderlust Travelogue</a>
       <ul class="right hide-on-med-and-down">
         <li><a href="sass.html"><i class="material-icons">search</i></a></li>
         <li><a href="badges.html"><i class="material-icons">view_module</i></a></li>
         <li><a href="collapsible.html"><i class="material-icons">refresh</i></a></li>
         <li><a href="mobile.html"><i class="material-icons">more_vert</i></a></li>
         <% if @current_user %>
              <li><%= link_to 'Sign Out', sign_in_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Sign In', sign_in_path %> </li>
         <% end %>
       </ul>
     </div>
   </nav>
<%= yield %>
<footer class="page-footer">
  <div class="container">
    <h5 class="white-text">
       <div class="wanderlust_icons">
        <i class="material-icons">airplanemode_active</i>
        <i class="material-icons">directions_walk</i>
        <i class="material-icons">favorite_border</i>
      </div>
    </h5>

    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">

  S. D O S S E T T  S W I F T
    © 2016 Copyright
    <a class="grey-text text-lighten-4 right" href="#!">PEACE LOVE AND ITCHY FEET</a>
    </div>
  </div>
</footer>

</body>
</html>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/new.html.erb
<div class="container">
  <div class="page-header">
      <h1>Sign Up and See the World</h1>
    </div>
  </div>

<% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% @user.errors.full_messages.each do |msg| %>
      <%= msg %><br>
    <% end %>
  </div>
<% end %>

<div class="container">

<%= form_for @user, url: create_user_path do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-lg btn-primary" %>
  </div>

<% end %>


</div>